### ISSUE TITLE
Don't use `readFileSync` to read wasm file

### ISSUE THREAD

**Issue by libre-man** [bokuweb/zstd-wasm#129]
Right now on node the library uses `readFileSync` to read the wasm file, this blocks the entire process while the wasm file is being read. Please use `fs/promises::readFile` instead which returns a promise. This change can be made (let me know if you want a PR) without any API change.

**Comment by bokuweb** [comment]
@libre-man Thanks. I see, could you please create PR?

**Comment by libre-man** [comment]
I've created the PR @bokuweb! Let me know if you need anything else!
