### ISSUE TITLE
Add dictionary support

### ISSUE THREAD

**Issue by AsyncBanana** [bokuweb/zstd-wasm#36]
It would be helpful for optimization if zstd dictionary support was added. Training is not needed, but it would be helpful to be able to pass a buffer representing the dictionary file.

**Comment by bokuweb** [comment]
@AsyncBanana Hi. Thanks for your proposal :)

> Would this increase the size of the WASM file though?

Yes. I want to reduce wasm/js file size as small as possible.
If `module linking` feature will be enabled in the future, it may resolve this issue.

**Comment by bokuweb** [comment]
@AsyncBanana  I misunderstood. dictionary is supported by #59
