### ISSUE TITLE
Not working with Node js (module) and exports unclear

### ISSUE THREAD

**Issue by Awendel** [bokuweb/zstd-wasm#83]
this project does not work for Node js via the newer ES6 Module import.

When importing via:

import * as zstd from "@bokuweb/zstd-wasm"

as suggested in the docs, 
it only exposed the compress / decompress API

MISSING are the following:
• compressUsingDict
• decompressUsingDict
• createCCtx
• createDCtx

please provide a simple **vanilla js** test example of how to access those resources in Node js when using as module

**Comment by bokuweb** [comment]
@Awendel use 0.0.17, and see https://github.com/bokuweb/zstd-wasm/blob/master/examples/node-esm-dict/index.mjs
